export const REGISTER_SUCCESS = "REGISTER_SUCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = " LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const ADD_PROFILE = 'ADD_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const FILTER_PROFILES = 'FILTER_PROFILES';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const CONTACT_ERROR = 'CONTACT_ERROR';

export const GET_PROFILES = 'GET_PROFILES';
export const CLEAR_PROFILES = 'CLEAR_PROFILES';
export const GET_ALLPROFILES = 'GET_ALLPROFILES';
export const ADD_NOTES = 'ADD_NOTES';
export const LIGHT_CANDLE = 'LIGHT_CANDLE'